[tool.black]
exclude = '^/(\.|dist|pybuild|venv|\.cci)'

[tool.coverage.report]
exclude_lines = ["pragma: no cover", "@abstract", ]

[tool.pytest.ini_options]
norecursedirs = [
    "node_modules",
    "venv",
    ".cci"
]